In [192]:
import numpy as np
import sqlite3
import pandas
import requests
import json
import csv

In [201]:
r = requests.get("https://icecube.wisc.edu/~grbweb_public/GRBweb2.sqlite")
f = open('GRBweb2.sqlite', 'wb').write(r.content)
db = sqlite3.connect('GRBweb2.sqlite')
table_names = pandas.read_sql_query("SELECT * from sqlite_sequence", db)

In [202]:
red_table = pandas.read_sql_query("SELECT * from Summary", db)
red_table = red_table.sort_values("redshift")
final_table = red_table[:687]
#red_table.iloc[8].to_numpy()[1] #name
#red_table.iloc[8].to_numpy()[2] #id
#red_table.iloc[8].to_numpy()[17] #redshift
#red_table.iloc[8].to_numpy()[18] #redshift source
#red_table.iloc[8].to_numpy()[19] #T100
output_fermi = {}
output_other = {}
fermi_id = []
for i in range(0, len(final_table)):
    array = final_table.iloc[i].to_numpy()
    grb_id = array[2]
    if grb_id == None:
        next_other = {"Name": array[1], "id": array[4], "redshift": array[17], "redshift_source": array[18], "T100": array[19]}
        output_other[array[1]] = next_other
    else:
        id_stripped = str(grb_id).split("B")[1]
        next_fermi = {"Name": array[1], "id": id_stripped, "redshift": array[17], "redshift_source": array[18], "T100": array[19]} 
        output_fermi[id_stripped] = next_fermi
        fermi_id.append({"id": id_stripped})
    #red_index = red_table.iloc[i].to_numpy()[0] - 1
    #red_val = red_table.iloc[i].redshift.get(red_index)
    #red_source = str(red_table.iloc[i].redshift_source.get(red_index))
    #t100 = red_table.iloc[i].T100.get(red_index)

other_str = json.dumps(output_other, indent=4)
with open("non_fermi.json", "w") as f:
    f.write(other_str)

fermi_str = json.dumps(output_fermi, indent=4)
with open("fermi.json", "w") as f:
    f.write(fermi_str)

print(other_str)
print(fermi_str)

with open('fermi_ids.csv', 'w', newline='') as csvfile:
    fieldnames = ['id']
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(fermi_id)

{
    "GRB980425A": {
        "Name": "GRB980425A",
        "id": "BeppoSAX",
        "redshift": 1.41e-06,
        "redshift_source": "BeppoSAX",
        "T100": 1.5e-07
    },
    "GRB250108A": {
        "Name": "GRB250108A",
        "id": "Swift",
        "redshift": NaN,
        "redshift_source": null,
        "T100": NaN
    },
    "GRB111005A": {
        "Name": "GRB111005A",
        "id": "GCN_circulars,Swift Det",
        "redshift": 6.2e-07,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB250106A": {
        "Name": "GRB250106A",
        "id": "Swift",
        "redshift": NaN,
        "redshift_source": null,
        "T100": NaN
    },
    "GRB060218A": {
        "Name": "GRB060218A",
        "id": "Swift",
        "redshift": 1.5699999999999998e-06,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB171205A": {
        "Name": "GRB171205A",
        "id": "GCN_circulars,Swift Det",
        "redshift": 3.6e-06,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB080121A": {
        "Name": "GRB080121A",
        "id": "Swift",
        "redshift": 3e-08,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB100316D": {
        "Name": "GRB100316D",
        "id": "GCN_circulars,Swift Det",
        "redshift": 3e-07,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB051109B": {
        "Name": "GRB051109B",
        "id": "Swift",
        "redshift": 2.56e-07,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB090417A": {
        "Name": "GRB090417A",
        "id": "GCN_circulars,Swift Det",
        "redshift": 1.8999999999999998e-08,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB060505A": {
        "Name": "GRB060505A",
        "id": "Swift",
        "redshift": 9.439999999999999e-07,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB080517A": {
        "Name": "GRB080517A",
        "id": "GCN_circulars,Swift Det",
        "redshift": 5.599999999999999e-07,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB110106A": {
        "Name": "GRB110106A",
        "id": "GCN_circulars,Swift Det",
        "redshift": 3e-07,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB091117A": {
        "Name": "GRB091117A",
        "id": "GCN_circulars,Konus-Wind Det",
        "redshift": NaN,
        "redshift_source": null,
        "T100": NaN
    },
    "GRB130822A": {
        "Name": "GRB130822A",
        "id": "GCN_circulars,Swift Det",
        "redshift": NaN,
        "redshift_source": null,
        "T100": NaN
    },
    "GRB061201A": {
        "Name": "GRB061201A",
        "id": "Swift",
        "redshift": 3.3399999999999995e-07,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB060614A": {
        "Name": "GRB060614A",
        "id": "Swift",
        "redshift": 2.0399999999999998e-05,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB230427A": {
        "Name": "GRB230427A",
        "id": "GCN_circulars,Swift Det",
        "redshift": NaN,
        "redshift_source": null,
        "T100": NaN
    },
    "GRB161219B": {
        "Name": "GRB161219B",
        "id": "GCN_circulars,Konus-Wind Det",
        "redshift": 1.5e-06,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB081211B": {
        "Name": "GRB081211B",
        "id": "Swift",
        "redshift": 6.1e-07,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB050509B": {
        "Name": "GRB050509B",
        "id": "Swift",
        "redshift": 9e-09,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB211227A": {
        "Name": "GRB211227A",
        "id": "GCN_circulars,MAXI Det",
        "redshift": 8e-06,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB210919A": {
        "Name": "GRB210919A",
        "id": "GCN_circulars,Swift Det",
        "redshift": 8.8e-08,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB191019A": {
        "Name": "GRB191019A",
        "id": "GCN_circulars,Swift Det",
        "redshift": 9.999999999999999e-06,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB150518A": {
        "Name": "GRB150518A",
        "id": "GCN_circulars,Konus-Wind Det",
        "redshift": NaN,
        "redshift_source": null,
        "T100": NaN
    },
    "GRB231117A": {
        "Name": "GRB231117A",
        "id": "GCN_circulars,Konus-Wind Det",
        "redshift": 2.3e-06,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB050724A": {
        "Name": "GRB050724A",
        "id": "Swift",
        "redshift": 9.98e-07,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB150818A": {
        "Name": "GRB150818A",
        "id": "GCN_circulars,Swift Det",
        "redshift": 4.1e-06,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB120422A": {
        "Name": "GRB120422A",
        "id": "GCN_circulars,Swift Det",
        "redshift": 2.2999999999999997e-07,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB060502B": {
        "Name": "GRB060502B",
        "id": "Swift",
        "redshift": 4e-08,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB250108B": {
        "Name": "GRB250108B",
        "id": "Swift",
        "redshift": NaN,
        "redshift_source": null,
        "T100": NaN
    },
    "GRB220219B": {
        "Name": "GRB220219B",
        "id": "GCN_circulars,IPN Triangulation",
        "redshift": NaN,
        "redshift_source": null,
        "T100": NaN
    },
    "GRB050826A": {
        "Name": "GRB050826A",
        "id": "Swift",
        "redshift": 4.1299999999999995e-07,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB111225A": {
        "Name": "GRB111225A",
        "id": "GCN_circulars,Swift Det",
        "redshift": 1.2999999999999998e-06,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB041219A": {
        "Name": "GRB041219A",
        "id": "Swift",
        "redshift": 0.000155,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB250424A": {
        "Name": "GRB250424A",
        "id": "GCN_circulars,Konus-Wind Det",
        "redshift": NaN,
        "redshift_source": null,
        "T100": NaN
    },
    "GRB090417B": {
        "Name": "GRB090417B",
        "id": "GCN_circulars,Swift Det",
        "redshift": 2.3e-06,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB061021A": {
        "Name": "GRB061021A",
        "id": "Swift",
        "redshift": 2.96e-06,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB210726A": {
        "Name": "GRB210726A",
        "id": "GCN_circulars,Swift Det",
        "redshift": 4.5e-08,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB140903A": {
        "Name": "GRB140903A",
        "id": "GCN_circulars,Swift Det",
        "redshift": 1.3999999999999998e-07,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB130603B": {
        "Name": "GRB130603B",
        "id": "GCN_circulars,Swift Det",
        "redshift": 6.3e-07,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB011121A": {
        "Name": "GRB011121A",
        "id": "BeppoSAX",
        "redshift": 9.83e-05,
        "redshift_source": "BeppoSAX",
        "T100": 7.7e-06
    },
    "GRB071227A": {
        "Name": "GRB071227A",
        "id": "Swift",
        "redshift": 2.2e-07,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB100628A": {
        "Name": "GRB100628A",
        "id": "GCN_circulars,Swift Det",
        "redshift": 2.5e-08,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB120714B": {
        "Name": "GRB120714B",
        "id": "GCN_circulars,Swift Det",
        "redshift": 1.2e-06,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB101225A": {
        "Name": "GRB101225A",
        "id": "GCN_circulars,Swift Det",
        "redshift": 1.9e-06,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB061210A": {
        "Name": "GRB061210A",
        "id": "Swift",
        "redshift": 1.11e-06,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB250322A": {
        "Name": "GRB250322A",
        "id": "GCN_circulars,Swift Det",
        "redshift": 1.5e-07,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB050803A": {
        "Name": "GRB050803A",
        "id": "Swift",
        "redshift": 2.1499999999999997e-06,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB201015A": {
        "Name": "GRB201015A",
        "id": "GCN_circulars,Swift Det",
        "redshift": 2e-07,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB990712A": {
        "Name": "GRB990712A",
        "id": "BeppoSAX",
        "redshift": 1.099e-05,
        "redshift_source": "BeppoSAX",
        "T100": 9.1e-07
    },
    "GRB061006A": {
        "Name": "GRB061006A",
        "id": "Swift",
        "redshift": 1.42e-06,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB181201A": {
        "Name": "GRB181201A",
        "id": "GCN_circulars,Fermi LAT Det",
        "redshift": NaN,
        "redshift_source": null,
        "T100": NaN
    },
    "GRB010921A": {
        "Name": "GRB010921A",
        "id": "BeppoSAX",
        "redshift": 1.34e-05,
        "redshift_source": "BeppoSAX",
        "T100": 1.7e-06
    },
    "GRB170428A": {
        "Name": "GRB170428A",
        "id": "GCN_circulars,Konus-Wind Det",
        "redshift": 2.7999999999999997e-07,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB070724A": {
        "Name": "GRB070724A",
        "id": "Swift",
        "redshift": 3e-08,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB230205A": {
        "Name": "GRB230205A",
        "id": "GCN_circulars,Swift Det",
        "redshift": 1.6e-07,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB111211A": {
        "Name": "GRB111211A",
        "id": "GCN_circulars,superAGILE",
        "redshift": NaN,
        "redshift_source": null,
        "T100": NaN
    },
    "GRB130831A": {
        "Name": "GRB130831A",
        "id": "GCN_circulars,Swift Det",
        "redshift": 6.5e-06,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB051117B": {
        "Name": "GRB051117B",
        "id": "Swift",
        "redshift": 1.7699999999999998e-07,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB100508A": {
        "Name": "GRB100508A",
        "id": "GCN_circulars,Swift Det",
        "redshift": 7e-07,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB081007A": {
        "Name": "GRB081007A",
        "id": "GCN_circulars,Fermi GBM Det",
        "redshift": 7.1e-07,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB060729A": {
        "Name": "GRB060729A",
        "id": "Swift",
        "redshift": 2.61e-06,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB100621A": {
        "Name": "GRB100621A",
        "id": "GCN_circulars,Swift Det",
        "redshift": 2.1e-05,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB051221A": {
        "Name": "GRB051221A",
        "id": "Swift",
        "redshift": 1.15e-06,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB200522A": {
        "Name": "GRB200522A",
        "id": "GCN_circulars,Swift Det",
        "redshift": NaN,
        "redshift_source": null,
        "T100": NaN
    },
    "GRB160425A": {
        "Name": "GRB160425A",
        "id": "GCN_circulars,Swift Det",
        "redshift": 2.1e-06,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB140710A": {
        "Name": "GRB140710A",
        "id": "GCN_circulars,Swift Det",
        "redshift": 2.2999999999999997e-07,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB180821A": {
        "Name": "GRB180821A",
        "id": "GCN_circulars,Swift Det",
        "redshift": 1.4e-06,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB050223A": {
        "Name": "GRB050223A",
        "id": "Swift",
        "redshift": 6.36e-07,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB150323A": {
        "Name": "GRB150323A",
        "id": "GCN_circulars,Swift Det",
        "redshift": 6.1e-06,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB131103A": {
        "Name": "GRB131103A",
        "id": "GCN_circulars,Swift Det",
        "redshift": 8.199999999999999e-07,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB100213B": {
        "Name": "GRB100213B",
        "id": "GCN_circulars,Swift Det",
        "redshift": NaN,
        "redshift_source": null,
        "T100": NaN
    },
    "GRB050525A": {
        "Name": "GRB050525A",
        "id": "Swift",
        "redshift": 1.53e-05,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB141212A": {
        "Name": "GRB141212A",
        "id": "GCN_circulars,Swift Det",
        "redshift": 7.2e-08,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB070612A": {
        "Name": "GRB070612A",
        "id": "Swift",
        "redshift": 1.06e-05,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB100418A": {
        "Name": "GRB100418A",
        "id": "GCN_circulars,Swift Det",
        "redshift": 3.4e-07,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB050416A": {
        "Name": "GRB050416A",
        "id": "Swift",
        "redshift": 3.67e-07,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB211023B": {
        "Name": "GRB211023B",
        "id": "GCN_circulars,Swift Det",
        "redshift": 1.7e-07,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB250704B": {
        "Name": "GRB250704B",
        "id": "Swift",
        "redshift": NaN,
        "redshift_source": null,
        "T100": NaN
    },
    "GRB111209A": {
        "Name": "GRB111209A",
        "id": "GCN_circulars,Konus-Wind Det",
        "redshift": 3.6e-05,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB020405A": {
        "Name": "GRB020405A",
        "id": "BeppoSAX",
        "redshift": 4.22e-05,
        "redshift_source": "BeppoSAX",
        "T100": 2.4e-06
    },
    "GRB970228A": {
        "Name": "GRB970228A",
        "id": "BeppoSAX",
        "redshift": 8.29e-06,
        "redshift_source": "BeppoSAX",
        "T100": 5.5e-07
    },
    "GRB090814A": {
        "Name": "GRB090814A",
        "id": "GCN_circulars,Swift Det",
        "redshift": 1.2999999999999998e-06,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB060904B": {
        "Name": "GRB060904B",
        "id": "Swift",
        "redshift": 1.62e-06,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB210210A": {
        "Name": "GRB210210A",
        "id": "GCN_circulars,Swift Det",
        "redshift": 9.8e-07,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB101219A": {
        "Name": "GRB101219A",
        "id": "GCN_circulars,Swift Det",
        "redshift": 4.5999999999999994e-07,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB160314A": {
        "Name": "GRB160314A",
        "id": "GCN_circulars,Swift Det",
        "redshift": 2.7999999999999997e-07,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB221006A": {
        "Name": "GRB221006A",
        "id": "GCN_circulars,MAXI Det",
        "redshift": NaN,
        "redshift_source": null,
        "T100": NaN
    },
    "GRB061110A": {
        "Name": "GRB061110A",
        "id": "Swift",
        "redshift": 1.06e-06,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB080430A": {
        "Name": "GRB080430A",
        "id": "GCN_circulars,Swift Det",
        "redshift": 1.2e-06,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB250430A": {
        "Name": "GRB250430A",
        "id": "GCN_circulars,Swift Det",
        "redshift": NaN,
        "redshift_source": null,
        "T100": NaN
    },
    "GRB250221A": {
        "Name": "GRB250221A",
        "id": "GCN_circulars,Swift Det",
        "redshift": NaN,
        "redshift_source": null,
        "T100": NaN
    },
    "GRB060202A": {
        "Name": "GRB060202A",
        "id": "Swift",
        "redshift": 2.13e-06,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB060602A": {
        "Name": "GRB060602A",
        "id": "Swift",
        "redshift": 1.61e-06,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB170714A": {
        "Name": "GRB170714A",
        "id": "GCN_circulars,Swift Det",
        "redshift": 2.8e-06,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB170519A": {
        "Name": "GRB170519A",
        "id": "GCN_circulars,Swift Det",
        "redshift": 1.1e-06,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB220813A": {
        "Name": "GRB220813A",
        "id": "GCN_circulars,Swift Det",
        "redshift": NaN,
        "redshift_source": null,
        "T100": NaN
    },
    "GRB070508A": {
        "Name": "GRB070508A",
        "id": "Swift",
        "redshift": 1.96e-05,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB110715A": {
        "Name": "GRB110715A",
        "id": "GCN_circulars,Swift Det",
        "redshift": 1.1799999999999999e-05,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB071112C": {
        "Name": "GRB071112C",
        "id": "Swift",
        "redshift": 3e-06,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB061217A": {
        "Name": "GRB061217A",
        "id": "Swift",
        "redshift": 4.2e-08,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB060123A": {
        "Name": "GRB060123A",
        "id": "Swift",
        "redshift": 3e-07,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB050824A": {
        "Name": "GRB050824A",
        "id": "Swift",
        "redshift": 2.66e-07,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB970508A": {
        "Name": "GRB970508A",
        "id": "BATSE",
        "redshift": 1.65e-06,
        "redshift_source": "BeppoSAX",
        "T100": 1.5e-07
    },
    "GRB070318A": {
        "Name": "GRB070318A",
        "id": "Swift",
        "redshift": 2.48e-06,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB990705A": {
        "Name": "GRB990705A",
        "id": "BeppoSAX",
        "redshift": 6.94e-05,
        "redshift_source": "BeppoSAX",
        "T100": 4.9e-06
    },
    "GRB250419A": {
        "Name": "GRB250419A",
        "id": "Swift",
        "redshift": NaN,
        "redshift_source": null,
        "T100": NaN
    },
    "GRB080710A": {
        "Name": "GRB080710A",
        "id": "GCN_circulars,Swift Det",
        "redshift": 1.4e-06,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB000210A": {
        "Name": "GRB000210A",
        "id": "BeppoSAX",
        "redshift": 4.8e-05,
        "redshift_source": "BeppoSAX",
        "T100": 3.7e-06
    },
    "GRB160117B": {
        "Name": "GRB160117B",
        "id": "GCN_circulars,Swift Det",
        "redshift": NaN,
        "redshift_source": null,
        "T100": NaN
    },
    "GRB070429B": {
        "Name": "GRB070429B",
        "id": "Swift",
        "redshift": 6.3e-08,
        "redshift_source": "Swift",
        "T100": NaN
    },
    "GRB070714B": {
        "Name": "GRB070714B",
        "id": "Swift",
        "redshift": 7.2e-07,

In [203]:
red_table[:687]

,id,GRB_name,GRB_name_Fermi,T0,T0_source,ra,ra_source,decl,decl_source,pos_error,...,fluence,fluence_source,fluence_error,fluence_error_source,redshift,redshift_source,T100,GBM_located,mjd,mjd_source
3759,3760,GRB980425A,None,38514.000,BeppoSAX,293.725000,IPN,-52.831667,IPN,0.133333,...,1.410000e-06,BeppoSAX,1.500000e-07,BeppoSAX,0.008500,IPN,22.000,0,50928.445764,BeppoSAX
3104,3105,GRB250108A,None,16621.513,Swift,207.921083,Swift,26.216500,Swift,0.000453,...,NaN,None,NaN,None,0.008884,Swift,NaN,0,60683.192379,Swift
1509,1510,GRB170817A,GRB170817529,45666.283,Fermi_GBM,191.750000,IPN,-39.800000,IPN,11.666667,...,2.791400e-07,Fermi_GBM,1.740300e-08,Fermi_GBM,0.009300,IPN,2.048,0,57982.528545,Fermi_GBM
635,636,GRB111005A,None,29114.000,"GCN_circulars,Swift Det",223.315000,Swift,-19.722000,Swift,0.016310,...,6.200000e-07,Swift,NaN,None,0.013130,None,26.000,0,55839.336968,"GCN_circulars,Swift Det"
3102,3103,GRB250106A,None,8959.972,Swift,117.238333,Swift,63.812417,Swift,0.000388,...,NaN,None,NaN,None,0.014999,Swift,NaN,0,60681.103703,Swift
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
520,521,GRB100905A,None,54494.000,"GCN_circulars,Swift Det",31.550167,Swift,14.929528,Swift,0.000194,...,1.700000e-07,Swift,NaN,None,7.900000,IPN,3.400,0,55444.630718,"GCN_circulars,Swift Det"
264,265,GRB090423A,GRB090423330,28519.000,"GCN_circulars,Swift Det",148.888583,Swift,18.149417,Swift,0.000181,...,8.164000e-07,Fermi_GBM,7.150000e-08,Fermi_GBM,8.000000,"GCN_circulars,GROND",10.300,0,54944.330081,"GCN_circulars,Swift Det"
338,339,GRB090709A,None,27514.000,"GCN_circulars,Swift Det",289.927000,Swift,60.727472,Swift,0.000181,...,2.570000e-05,Swift,NaN,None,8.500000,"GCN_circulars,Swift-BAT Det",89.000,0,55021.318449,"GCN_circulars,Swift Det"
270,271,GRB090429B,None,19803.000,"GCN_circulars,Swift Det",210.667125,Swift,32.170528,Swift,0.000194,...,3.100000e-07,Swift,NaN,None,9.400000,"GCN_circulars,Swift Other",5.500,0,54950.229201,"GCN_circulars,Swift Det"
434,435,GRB100205A,None,15523.000,"GCN_circulars,Swift Det",141.387667,Swift,31.740083,Swift,0.000220,...,4.000000e-07,Swift,NaN,None,11.000000,"GCN_circulars,Other",26.000,0,55232.179664,"GCN_circulars,Swift Det"

In [204]:
def checkRed(fermiID):
    name_Fermi = "GRB" + fermiID
    t100 = 0
    red_val = 0
    red_source = ""
    try:
        check_table = pandas.read_sql_query("SELECT * from Summary", db)
        check_table = check_table.sort_values("GRB_name")
        indices = np.where(check_table == name_Fermi)
        row_indices, col_indices = indices[0], indices[1]
        red_index = check_table.iloc[row_indices].to_numpy()[0][0] - 1
        red_val = check_table.iloc[row_indices].redshift.get(red_index)
        red_source = str(check_table.iloc[row_indices].redshift_source.get(red_index))
        t100 = check_table.iloc[row_indices].T100.get(red_index)
    finally:
        return [name_Fermi, t100, red_val, red_source]

In [207]:
GRB_name= "GRB251202077"

In [209]:
Sum_table = pandas.read_sql_query("SELECT * from Summary", db)
Sum_table = Sum_table.sort_values("GRB_name")
indices = np.where(Sum_table == GRB_name)
# Extracting row and column indices
row_indices, col_indices = indices[0], indices[1]
#print(row_indices, col_indices)
Sum_table.iloc[row_indices]
#index = Sum_table.iloc[row_indices].to_numpy()[0][0] - 1
#Sum_table.iloc[row_indices].redshift.get(index)
#float(Sum_table.iloc[row_indices].redshift)
#Sum_table.iloc[row_indices].redshift_source

,id,GRB_name,GRB_name_Fermi,T0,T0_source,ra,ra_source,decl,decl_source,pos_error,...,fluence,fluence_source,fluence_error,fluence_error_source,redshift,redshift_source,T100,GBM_located,mjd,mjd_source
3384,3385,GRB251202A,GRB251202077,6646.674,Fermi_GBM,122.114583,"GCN_circulars,Swift-UVOT Det",40.612583,"GCN_circulars,Swift-UVOT Det",NaN,...,0.000009,Fermi_GBM,7.816200e-08,Fermi_GBM,2.785,None,43.008,0,61011.076929,Fermi_GBM

In [113]:
t_index = Sum_table.iloc[row_indices].to_numpy()[0][0] - 1
test100 = Sum_table.iloc[row_indices].T100.get(t_index)
test_red_src = str(Sum_table.iloc[row_indices].redshift_source.get(t_index))
[test100,test_red_src]

[np.float64(16.923), 'GCN_circulars,Other']

In [114]:
checkRed("090926181")

['GRB090926181', np.float64(16.923), np.float64(2.1062), 'GCN_circulars,Other']

In [115]:
checkRed("090926182")

['GRB090926182', 0, 0, '']

In [138]:
def checkID(ID, return_object):
    result = []
    for i in range(0, 999):
        addendum = str(i)
        if i < 100:
            addendum = "0" + str(i)
        elif i < 10:
            addendum = "00" + str(i)
        name_Fermi = str(ID) + addendum

        output = checkRed(name_Fermi)
        if output[1] != 0:
            result = output
    
    if result[1] != 0:
        return_object[result[0]] = [result[1],result[2],result[3]]
        return return_object
    else:
        return "Error 1: checkFailed"

In [139]:
object_test = {}
print(object_test)
nextver = checkID("090926", object_test)
if nextver != "Error 1: checkFailed":
    object_test = nextver
nextver = checkID("090927", object_test)
if nextver != "Error 1: checkFailed":
    object_test = nextver
print(object_test)

{}
{'GRB090926914': [np.float64(129.175), np.float64(1.24), 'None'], 'GRB090927422': [np.float64(2.2), np.float64(1.37), 'None']}

In [140]:
checkID("090926", {})

{'GRB090926914': [np.float64(129.175), np.float64(1.24), 'None']}