In [24]:
import numpy as np
import sqlite3
import pandas
import requests

In [25]:
r = requests.get("https://icecube.wisc.edu/~grbweb_public/GRBweb2.sqlite")
f = open('GRBweb2.sqlite', 'wb').write(r.content)

In [26]:
db = sqlite3.connect('GRBweb2.sqlite')

In [84]:
Sum_table = pandas.read_sql_query("SELECT * from Summary", db)
Sum_table = Sum_table.sort_values("GRB_name")
indices = np.where(Sum_table == "GRB140619B")
row_indices, col_indices = indices[0], indices[1]
index = Sum_table.iloc[row_indices].to_numpy()[0][0] - 1

#Sum_table.iloc[row_indices].T100.get(index)
#Sum_table.iloc[row_indices].T0.get(index)
#Sum_table.iloc[row_indices].GRB_name.get(index)
Sum_table.iloc[row_indices]

,id,GRB_name,GRB_name_Fermi,T0,T0_source,ra,ra_source,decl,decl_source,pos_error,...,fluence,fluence_source,fluence_error,fluence_error_source,redshift,redshift_source,T100,GBM_located,mjd,mjd_source
1032,1033,GRB140619B,GRB140619475,41080.264,Fermi_GBM,132.68,Fermi_LAT,-9.66,Fermi_LAT,0.06,...,0.000002,Fermi_GBM,6.953700e-08,Fermi_GBM,NaN,NaN,2.816,0,56827.475466,Fermi_GBM

In [ ]:
#Summary => 740

In [83]:
Big_table = pandas.read_sql_query("SELECT * from Summary", db)
Big_table = Big_table.sort_values("redshift", ascending=False)
Second = Big_table[:740].sort_values("GRB_name_Fermi", ascending=False)
final = Second[:275]

names = final["GRB_name_Fermi"]
big_list = []
for i in names:
    print(i)
    big_list.append(i.split("B")[1])

final

GRB260208214
GRB260131277
GRB260114486
GRB260101039
GRB251222712
GRB251214377
GRB251202077
GRB251201685
GRB251103199
GRB251026305
GRB251013736
GRB251003082
GRB251002844
GRB251001595
GRB250920643
GRB250920366
GRB250919020
GRB250916562
GRB250813952
GRB250725077
GRB250716062
GRB250702880
GRB250625670
GRB250617876
GRB250506100
GRB250407659
GRB250404597
GRB250403636
GRB250402964
GRB250316375
GRB250309318
GRB250226274
GRB250225819
GRB250215105
GRB250205893
GRB250103415
GRB241228176
GRB241209233
GRB241105671
GRB241030774
GRB241030242
GRB241029097
GRB241026946
GRB241025067
GRB240916058
GRB240912074
GRB240910167
GRB240825662
GRB240821775
GRB240619155
GRB240514169
GRB240511754
GRB240414098
GRB240218084
GRB240209263
GRB240205926
GRB240118075
GRB231215408
GRB231118720
GRB231024556
GRB230818977
GRB230812790
GRB230328621
GRB230307656
GRB230204906
GRB221226945
GRB221009553
GRB220627890
GRB220527387
GRB220521972
GRB220211047
GRB220107615
GRB220101215
GRB211211549
GRB211023546
GRB211018936
GRB210826293
GRB210731931
GRB210722871
GRB210704815
GRB210619999
GRB210610827
GRB210610628
GRB210606164
GRB210510806
GRB210323918
GRB210204270
GRB210104477
GRB201221963
GRB201216963
GRB201104808
GRB201021852
GRB201020732
GRB201020241
GRB200829582
GRB200826187
GRB200817393
GRB200613229
GRB200524211
GRB200411187
GRB200219317
GRB191011192
GRB190829830
GRB190719624
GRB190324947
GRB190114873
GRB181020792
GRB181010247
GRB180805543
GRB180728728
GRB180727594
GRB180720598
GRB180703876
GRB180620660
GRB180618030
GRB180418281
GRB180314030
GRB180205184
GRB171222684
GRB171010792
GRB170903534
GRB170817529
GRB170728961
GRB170705115
GRB170607971
GRB170405777
GRB170214649
GRB170127634
GRB170113420
GRB161129300
GRB161117066
GRB161017745
GRB161014522
GRB161001045
GRB160821937
GRB160804065
GRB160629930
GRB160625945
GRB160624477
GRB160623209
GRB160509374
GRB160411062
GRB160408268
GRB160104475
GRB151229285
GRB151111356
GRB151027166
GRB150821406
GRB150727793
GRB150514774
GRB150403913
GRB150314205
GRB150301818
GRB150120123
GRB150101641
GRB141225959
GRB141221338
GRB141220252
GRB141118678
GRB141028455
GRB141004973
GRB140907672
GRB140906175
GRB140829880
GRB140808038
GRB140801792
GRB140713780
GRB140703026
GRB140623224
GRB140620219
GRB140606133
GRB140512814
GRB140508128
GRB140506880
GRB140423356
GRB140408553
GRB140304557
GRB140213807
GRB140206304
GRB140108721
GRB131231198
GRB131229277
GRB131202633
GRB131108862
GRB131105087
GRB131011741
GRB131004904
GRB130925164
GRB130907904
GRB130716442
GRB130702004
GRB130612141
GRB130610133
GRB130518580
GRB130515056
GRB130427324
GRB130420313
GRB130215063
GRB121217313
GRB121211574
GRB121128212
GRB121123421
GRB121031949
GRB121011469
GRB120922939
GRB120909070
GRB120907017
GRB120811649
GRB120729456
GRB120716712
GRB120712571
GRB120711115
GRB120707800
GRB120624933
GRB120326056
GRB120302080
GRB120119170
GRB120118709
GRB111228657
GRB111117510
GRB111107035
GRB110818860
GRB110731465
GRB110721200
GRB110402009
GRB110213220
GRB110128073
GRB110106893
GRB101224227
GRB101219686
GRB101213451
GRB100906576
GRB100816026
GRB100814160
GRB100728439
GRB100728095
GRB100704149
GRB100625773
GRB100615083
GRB100414097
GRB100413732
GRB100216422
GRB100206563
GRB100117879
GRB091208410
GRB091127976
GRB091024372
GRB091020900
GRB091003191
GRB090927422
GRB090926914
GRB090926181
GRB090902462
GRB090618353
GRB090519881
GRB090516353
GRB090510016
GRB090424592
GRB090423330
GRB090328401
GRB090323002
GRB090113778
GRB090102122
GRB081222204
GRB081221681
GRB081121858
GRB081109293
GRB081008832
GRB080928628
GRB080916406
GRB080916009
GRB080905705
GRB080905499
GRB080810549
GRB080804972

,id,GRB_name,GRB_name_Fermi,T0,T0_source,ra,ra_source,decl,decl_source,pos_error,...,fluence,fluence_source,fluence_error,fluence_error_source,redshift,redshift_source,T100,GBM_located,mjd,mjd_source
3431,3432,GRB260208A,GRB260208214,18448.000,"GCN_circulars,Fermi GBM final loc",204.731500,"GCN_circulars,Swift-XRT Other",33.801120,"GCN_circulars,Swift-XRT Other",NaN,...,1.343200e-04,Fermi_GBM,1.031400e-07,Fermi_GBM,2.3600,NaN,41.972,0,61079.213519,"GCN_circulars,Fermi GBM final loc"
3427,3428,GRB260131A,GRB260131277,23970.000,"GCN_circulars,Fermi GBM final loc",24.713819,"GCN_circulars,Optical",34.328119,"GCN_circulars,Optical",NaN,...,2.581200e-05,Fermi_GBM,1.322300e-07,Fermi_GBM,1.4340,"GCN_circulars,Optical",257.082,0,61071.277431,"GCN_circulars,Fermi GBM final loc"
3416,3417,GRB260114A,GRB260114486,42026.000,"GCN_circulars,Swift Det",74.598292,Swift,-8.014333,Swift,0.000427,...,4.650700e-06,Fermi_GBM,2.164600e-08,Fermi_GBM,0.5240,NaN,0.566,0,61054.486412,"GCN_circulars,Swift Det"
3404,3405,GRB260101A,GRB260101039,3390.000,"GCN_circulars,Fermi GBM Det",86.429000,Swift,63.592250,Swift,0.000056,...,7.071400e-06,Fermi_GBM,1.981900e-08,Fermi_GBM,2.6230,NaN,28.298,0,61041.039236,"GCN_circulars,Fermi GBM Det"
3400,3401,GRB251222A,GRB251222712,61541.154,Fermi_GBM,77.212500,IPN,-7.216667,IPN,0.060000,...,1.205500e-05,Fermi_GBM,1.551000e-07,Fermi_GBM,3.1710,"GCN_circulars,Optical",86.978,0,61031.712282,Fermi_GBM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,GRB080916C,GRB080916009,764.632,"GCN_circulars,Konus-Wind Det",119.847170,Fermi_LAT,-56.638333,Fermi_LAT,0.000139,...,6.027200e-05,Fermi_GBM,6.997200e-08,Fermi_GBM,4.3500,IPN,65.239,0,54725.008850,"GCN_circulars,Konus-Wind Det"
85,86,GRB080905B,GRB080905705,60941.723,Fermi_GBM,301.741208,Swift,-62.563056,Swift,0.000091,...,2.909300e-06,Fermi_GBM,3.634600e-08,Fermi_GBM,2.3740,NaN,131.277,0,54714.705344,Fermi_GBM
84,85,GRB080905A,GRB080905499,43134.000,"GCN_circulars,Swift Det",287.674083,Swift,-18.880167,Swift,0.000207,...,8.504600e-07,Fermi_GBM,4.621700e-08,Fermi_GBM,0.1218,NaN,1.934,0,54714.499236,"GCN_circulars,Swift Det"
77,78,GRB080810A,GRB080810549,47409.381,Fermi_GBM,356.792750,Swift,0.319806,Swift,0.000078,...,9.439800e-06,Fermi_GBM,4.895700e-08,Fermi_GBM,3.3500,"GCN_circulars,Optical",108.619,0,54688.548720,Fermi_GBM
75,76,GRB080804A,GRB080804972,84014.000,"GCN_circulars,Swift Det",328.667500,Swift,-53.184611,Swift,0.000052,...,9.129400e-06,Fermi_GBM,1.058900e-07,Fermi_GBM,2.2045,NaN,34.000,0,54682.972384,"GCN_circulars,Swift Det"

In [55]:
GRB_name = "GRB100205A"
Fermi_table = pandas.read_sql_query("SELECT * from Fermi_LAT", db)
Fermi_table = Fermi_table.sort_values("GRB_name")
indices = np.where(Fermi_table == GRB_name)
# Extracting row and column indices
row_indices, col_indices = indices[0], indices[1]
print(row_indices, col_indices)
Fermi_table.iloc[row_indices]

[] []

Empty DataFrame
Columns: [id, GRB_name_Fermi, GRB_name, MET, datum, t_trigger, ra, decl, pos_error]
Index: []